#ifndef APP_ICONS_H
#define APP_ICONS_H

#define APP_ICONS_ATLAS_WIDTH 15
#define APP_ICONS_ATLAS_HEIGHT 1

#define APP_ICONS_MIN 61440
#define APP_ICONS_MAX 61455

#define ICON_FEATURE_BURIED_TREASURE u8"\uf000"
#define ICON_VAL_FEATURE_BURIED_TREASURE 0xF000
#define ICON_FEATURE_DESERT_PYRAMID u8"\uf001"
#define ICON_VAL_FEATURE_DESERT_PYRAMID 0xF001
#define ICON_FEATURE_END_CITY u8"\uf002"
#define ICON_VAL_FEATURE_END_CITY 0xF002
#define ICON_FEATURE_IGLOO u8"\uf003"
#define ICON_VAL_FEATURE_IGLOO 0xF003
#define ICON_FEATURE_JUNGLE_TEMPLE u8"\uf004"
#define ICON_VAL_FEATURE_JUNGLE_TEMPLE 0xF004
#define ICON_FEATURE_MINESHAFT u8"\uf005"
#define ICON_VAL_FEATURE_MINESHAFT 0xF005
#define ICON_FEATURE_NETHER_FORTRESS u8"\uf006"
#define ICON_VAL_FEATURE_NETHER_FORTRESS 0xF006
#define ICON_FEATURE_OCEAN_MONUMENT u8"\uf007"
#define ICON_VAL_FEATURE_OCEAN_MONUMENT 0xF007
#define ICON_FEATURE_OCEAN_RUIN u8"\uf008"
#define ICON_VAL_FEATURE_OCEAN_RUIN 0xF008
#define ICON_FEATURE_PILLAGER_OUTPOST u8"\uf009"
#define ICON_VAL_FEATURE_PILLAGER_OUTPOST 0xF009
#define ICON_FEATURE_SHIPWRECK u8"\uf00a"
#define ICON_VAL_FEATURE_SHIPWRECK 0xF00A
#define ICON_FEATURE_STRONGHOLD u8"\uf00b"
#define ICON_VAL_FEATURE_STRONGHOLD 0xF00B
#define ICON_FEATURE_VILLAGE u8"\uf00c"
#define ICON_VAL_FEATURE_VILLAGE 0xF00C
#define ICON_FEATURE_WITCH_HUT u8"\uf00d"
#define ICON_VAL_FEATURE_WITCH_HUT 0xF00D
#define ICON_FEATURE_WOODLAND_MANSION u8"\uf00e"
#define ICON_VAL_FEATURE_WOODLAND_MANSION 0xF00E

#endif